export const REGISTER_ORGANIZATION_SUCCESS = 'REGISTER_ORGANIZATION_SUCCESS';
export const REGISTER_ORGANIZATION_FAIL = 'REGISTER_ORGANIZATION_FAIL';

export const LOGOUT_ORGANIZATION_SUCCESS = 'LOGOUT_ORGANIZATION_SUCCESS';
export const LOGOUT_ORGANIZATION_FAIL = 'LOGOUT_ORGANIZATION_FAIL';

export const LOGIN_ORGANIZATION_SUCCESS = 'LOGIN_ORGANIZATION_SUCCESS';
export const LOGIN_ORGANIZATION_FAIL = 'LOGIN_ORGANIZATION_FAIL';

export const ADD_NEW_COURSE_SUCCESS = 'ADD_NEW_COURSE_SUCCESS';
export const ADD_NEW_COURSE_FAIL = 'ADD_NEW_COURSE_FAIL';
