export const GET_CURRENT_USER = 'GET_CURRENT_USER';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL';

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const ADD_TO_FAV_USER_SUCCESS = 'ADD_TO_FAV_USER_SUCCESS';
export const ADD_TO_FAV_USER_FAIL = 'ADD_TO_FAV_USER_FAIL';

export const REMOVE_FROM_FAV_USER_SUCCESS = 'REMOVE_FROM_FAV_USER_SUCCESS';
export const REMOVE_FROM_FAV_USER_FAIL = 'REMOVE_FROM_FAV_USER_FAIL';

export const ADD_REQUEST_USER_SUCCESS = 'ADD_REQUEST_USER_SUCCESS';
export const ADD_REQUEST_USER_FAIL = 'ADD_REQUEST_USER_FAIL';

export const REMOVE_REQUEST_USER_SUCCESS = 'REMOVE_REQUEST_USER_SUCCESS';
export const REMOVE_REQUEST_USER_FAIL = 'REMOVE_REQUEST_USER_FAIL';
